// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zeqbonuoleinusefkuzd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplcWJvbnVvbGVpbnVzZWZrdXpkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5MTgzNTAsImV4cCI6MjA2NzQ5NDM1MH0.cdd7cbeZuCtEO3Z5K47bPPVBVXBqfR0GZBGNg3vYGmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});